
package fr.afcepf.ai102.monservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MonPremierService", targetNamespace = "http://monservice.ai102.afcepf.fr", wsdlLocation = "http://localhost:18080/PremierService_JAXWS/MonPremierService/CalculSW?wsdl")
public class MonPremierService
    extends Service
{

    private final static URL MONPREMIERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MONPREMIERSERVICE_EXCEPTION;
    private final static QName MONPREMIERSERVICE_QNAME = new QName("http://monservice.ai102.afcepf.fr", "MonPremierService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/PremierService_JAXWS/MonPremierService/CalculSW?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONPREMIERSERVICE_WSDL_LOCATION = url;
        MONPREMIERSERVICE_EXCEPTION = e;
    }

    public MonPremierService() {
        super(__getWsdlLocation(), MONPREMIERSERVICE_QNAME);
    }

    public MonPremierService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONPREMIERSERVICE_QNAME, features);
    }

    public MonPremierService(URL wsdlLocation) {
        super(wsdlLocation, MONPREMIERSERVICE_QNAME);
    }

    public MonPremierService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONPREMIERSERVICE_QNAME, features);
    }

    public MonPremierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonPremierService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICalcul
     */
    @WebEndpoint(name = "IMonInterfaceDeService")
    public ICalcul getIMonInterfaceDeService() {
        return super.getPort(new QName("http://monservice.ai102.afcepf.fr", "IMonInterfaceDeService"), ICalcul.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICalcul
     */
    @WebEndpoint(name = "IMonInterfaceDeService")
    public ICalcul getIMonInterfaceDeService(WebServiceFeature... features) {
        return super.getPort(new QName("http://monservice.ai102.afcepf.fr", "IMonInterfaceDeService"), ICalcul.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MONPREMIERSERVICE_EXCEPTION!= null) {
            throw MONPREMIERSERVICE_EXCEPTION;
        }
        return MONPREMIERSERVICE_WSDL_LOCATION;
    }

}
