//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerService.fr.afcepf.ai102.service.java {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://monservice.ai102.afcepf.fr", ConfigurationName="fr.afcepf.ai102.service.java.ICalcul")]
    public interface ICalcul {
        
        // CODEGEN : Le paramètre 'resultatAddition' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultatAddition")]
        ConsumerService.fr.afcepf.ai102.service.java.ajouterResponse ajouter(ConsumerService.fr.afcepf.ai102.service.java.ajouter request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.java.ajouterResponse> ajouterAsync(ConsumerService.fr.afcepf.ai102.service.java.ajouter request);
        
        // CODEGEN : Le paramètre 'leToto' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="leToto")]
        ConsumerService.fr.afcepf.ai102.service.java.getTotoResponse getToto(ConsumerService.fr.afcepf.ai102.service.java.getToto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.java.getTotoResponse> getTotoAsync(ConsumerService.fr.afcepf.ai102.service.java.getToto request);
        
        // CODEGEN : Le paramètre 'resultatPuissance' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultatPuissance")]
        ConsumerService.fr.afcepf.ai102.service.java.puissanceResponse puissance(ConsumerService.fr.afcepf.ai102.service.java.puissance request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.java.puissanceResponse> puissanceAsync(ConsumerService.fr.afcepf.ai102.service.java.puissance request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouter", WrapperNamespace="http://monservice.ai102.afcepf.fr", IsWrapped=true)]
    public partial class ajouter {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monservice.ai102.afcepf.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int unEntier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monservice.ai102.afcepf.fr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int unAutreEntier;
        
        public ajouter() {
        }
        
        public ajouter(int unEntier, int unAutreEntier) {
            this.unEntier = unEntier;
            this.unAutreEntier = unAutreEntier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterResponse", WrapperNamespace="http://monservice.ai102.afcepf.fr", IsWrapped=true)]
    public partial class ajouterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monservice.ai102.afcepf.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int resultatAddition;
        
        public ajouterResponse() {
        }
        
        public ajouterResponse(int resultatAddition) {
            this.resultatAddition = resultatAddition;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monservice.ai102.afcepf.fr")]
    public partial class foo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomField;
        
        private string prenomField;
        
        private int identifiantField;
        
        private bool identifiantFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                this.prenomField = value;
                this.RaisePropertyChanged("prenom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int identifiant {
            get {
                return this.identifiantField;
            }
            set {
                this.identifiantField = value;
                this.RaisePropertyChanged("identifiant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool identifiantSpecified {
            get {
                return this.identifiantFieldSpecified;
            }
            set {
                this.identifiantFieldSpecified = value;
                this.RaisePropertyChanged("identifiantSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getToto", WrapperNamespace="http://monservice.ai102.afcepf.fr", IsWrapped=true)]
    public partial class getToto {
        
        public getToto() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTotoResponse", WrapperNamespace="http://monservice.ai102.afcepf.fr", IsWrapped=true)]
    public partial class getTotoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monservice.ai102.afcepf.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsumerService.fr.afcepf.ai102.service.java.foo leToto;
        
        public getTotoResponse() {
        }
        
        public getTotoResponse(ConsumerService.fr.afcepf.ai102.service.java.foo leToto) {
            this.leToto = leToto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="puissance", WrapperNamespace="http://monservice.ai102.afcepf.fr", IsWrapped=true)]
    public partial class puissance {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monservice.ai102.afcepf.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double unDouble;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monservice.ai102.afcepf.fr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double unAutreDouble;
        
        public puissance() {
        }
        
        public puissance(double unDouble, double unAutreDouble) {
            this.unDouble = unDouble;
            this.unAutreDouble = unAutreDouble;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="puissanceResponse", WrapperNamespace="http://monservice.ai102.afcepf.fr", IsWrapped=true)]
    public partial class puissanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monservice.ai102.afcepf.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double resultatPuissance;
        
        public puissanceResponse() {
        }
        
        public puissanceResponse(double resultatPuissance) {
            this.resultatPuissance = resultatPuissance;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculChannel : ConsumerService.fr.afcepf.ai102.service.java.ICalcul, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculClient : System.ServiceModel.ClientBase<ConsumerService.fr.afcepf.ai102.service.java.ICalcul>, ConsumerService.fr.afcepf.ai102.service.java.ICalcul {
        
        public CalculClient() {
        }
        
        public CalculClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerService.fr.afcepf.ai102.service.java.ajouterResponse ConsumerService.fr.afcepf.ai102.service.java.ICalcul.ajouter(ConsumerService.fr.afcepf.ai102.service.java.ajouter request) {
            return base.Channel.ajouter(request);
        }
        
        public int ajouter(int unEntier, int unAutreEntier) {
            ConsumerService.fr.afcepf.ai102.service.java.ajouter inValue = new ConsumerService.fr.afcepf.ai102.service.java.ajouter();
            inValue.unEntier = unEntier;
            inValue.unAutreEntier = unAutreEntier;
            ConsumerService.fr.afcepf.ai102.service.java.ajouterResponse retVal = ((ConsumerService.fr.afcepf.ai102.service.java.ICalcul)(this)).ajouter(inValue);
            return retVal.resultatAddition;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.java.ajouterResponse> ConsumerService.fr.afcepf.ai102.service.java.ICalcul.ajouterAsync(ConsumerService.fr.afcepf.ai102.service.java.ajouter request) {
            return base.Channel.ajouterAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.java.ajouterResponse> ajouterAsync(int unEntier, int unAutreEntier) {
            ConsumerService.fr.afcepf.ai102.service.java.ajouter inValue = new ConsumerService.fr.afcepf.ai102.service.java.ajouter();
            inValue.unEntier = unEntier;
            inValue.unAutreEntier = unAutreEntier;
            return ((ConsumerService.fr.afcepf.ai102.service.java.ICalcul)(this)).ajouterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerService.fr.afcepf.ai102.service.java.getTotoResponse ConsumerService.fr.afcepf.ai102.service.java.ICalcul.getToto(ConsumerService.fr.afcepf.ai102.service.java.getToto request) {
            return base.Channel.getToto(request);
        }
        
        public ConsumerService.fr.afcepf.ai102.service.java.foo getToto() {
            ConsumerService.fr.afcepf.ai102.service.java.getToto inValue = new ConsumerService.fr.afcepf.ai102.service.java.getToto();
            ConsumerService.fr.afcepf.ai102.service.java.getTotoResponse retVal = ((ConsumerService.fr.afcepf.ai102.service.java.ICalcul)(this)).getToto(inValue);
            return retVal.leToto;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.java.getTotoResponse> ConsumerService.fr.afcepf.ai102.service.java.ICalcul.getTotoAsync(ConsumerService.fr.afcepf.ai102.service.java.getToto request) {
            return base.Channel.getTotoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.java.getTotoResponse> getTotoAsync() {
            ConsumerService.fr.afcepf.ai102.service.java.getToto inValue = new ConsumerService.fr.afcepf.ai102.service.java.getToto();
            return ((ConsumerService.fr.afcepf.ai102.service.java.ICalcul)(this)).getTotoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerService.fr.afcepf.ai102.service.java.puissanceResponse ConsumerService.fr.afcepf.ai102.service.java.ICalcul.puissance(ConsumerService.fr.afcepf.ai102.service.java.puissance request) {
            return base.Channel.puissance(request);
        }
        
        public double puissance(double unDouble, double unAutreDouble) {
            ConsumerService.fr.afcepf.ai102.service.java.puissance inValue = new ConsumerService.fr.afcepf.ai102.service.java.puissance();
            inValue.unDouble = unDouble;
            inValue.unAutreDouble = unAutreDouble;
            ConsumerService.fr.afcepf.ai102.service.java.puissanceResponse retVal = ((ConsumerService.fr.afcepf.ai102.service.java.ICalcul)(this)).puissance(inValue);
            return retVal.resultatPuissance;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.java.puissanceResponse> ConsumerService.fr.afcepf.ai102.service.java.ICalcul.puissanceAsync(ConsumerService.fr.afcepf.ai102.service.java.puissance request) {
            return base.Channel.puissanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.java.puissanceResponse> puissanceAsync(double unDouble, double unAutreDouble) {
            ConsumerService.fr.afcepf.ai102.service.java.puissance inValue = new ConsumerService.fr.afcepf.ai102.service.java.puissance();
            inValue.unDouble = unDouble;
            inValue.unAutreDouble = unAutreDouble;
            return ((ConsumerService.fr.afcepf.ai102.service.java.ICalcul)(this)).puissanceAsync(inValue);
        }
    }
}
