//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerService.fr.afcepf.ai102.service.dotnet {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Toto", Namespace="http://dotnet.service.ai102.afcepf.fr/")]
    [System.SerializableAttribute()]
    public partial class Toto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dotnet.service.ai102.afcepf.fr/", ConfigurationName="fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap")]
    public interface PremierServiceDotNetSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://dotnet.service.ai102.afcepf.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnet.service.ai102.afcepf.fr/HelloWorld", ReplyAction="*")]
        ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldResponse HelloWorld(ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnet.service.ai102.afcepf.fr/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldResponse> HelloWorldAsync(ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnet.service.ai102.afcepf.fr/ajouter", ReplyAction="*")]
        int ajouter(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnet.service.ai102.afcepf.fr/ajouter", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ajouterAsync(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnet.service.ai102.afcepf.fr/puissance", ReplyAction="*")]
        double puissance(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnet.service.ai102.afcepf.fr/puissance", ReplyAction="*")]
        System.Threading.Tasks.Task<double> puissanceAsync(double a, double b);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetTotoResult de l'espace de noms http://dotnet.service.ai102.afcepf.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnet.service.ai102.afcepf.fr/GetToto", ReplyAction="*")]
        ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoResponse GetToto(ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnet.service.ai102.afcepf.fr/GetToto", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoResponse> GetTotoAsync(ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://dotnet.service.ai102.afcepf.fr/", Order=0)]
        public ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://dotnet.service.ai102.afcepf.fr/", Order=0)]
        public ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dotnet.service.ai102.afcepf.fr/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToto", Namespace="http://dotnet.service.ai102.afcepf.fr/", Order=0)]
        public ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequestBody Body;
        
        public GetTotoRequest() {
        }
        
        public GetTotoRequest(ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTotoRequestBody {
        
        public GetTotoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotoResponse", Namespace="http://dotnet.service.ai102.afcepf.fr/", Order=0)]
        public ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoResponseBody Body;
        
        public GetTotoResponse() {
        }
        
        public GetTotoResponse(ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dotnet.service.ai102.afcepf.fr/")]
    public partial class GetTotoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumerService.fr.afcepf.ai102.service.dotnet.Toto GetTotoResult;
        
        public GetTotoResponseBody() {
        }
        
        public GetTotoResponseBody(ConsumerService.fr.afcepf.ai102.service.dotnet.Toto GetTotoResult) {
            this.GetTotoResult = GetTotoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PremierServiceDotNetSoapChannel : ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PremierServiceDotNetSoapClient : System.ServiceModel.ClientBase<ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap>, ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap {
        
        public PremierServiceDotNetSoapClient() {
        }
        
        public PremierServiceDotNetSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PremierServiceDotNetSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PremierServiceDotNetSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PremierServiceDotNetSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldResponse ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap.HelloWorld(ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequest inValue = new ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequest();
            inValue.Body = new ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequestBody();
            ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldResponse retVal = ((ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldResponse> ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap.HelloWorldAsync(ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldResponse> HelloWorldAsync() {
            ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequest inValue = new ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequest();
            inValue.Body = new ConsumerService.fr.afcepf.ai102.service.dotnet.HelloWorldRequestBody();
            return ((ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int ajouter(int i, int j) {
            return base.Channel.ajouter(i, j);
        }
        
        public System.Threading.Tasks.Task<int> ajouterAsync(int i, int j) {
            return base.Channel.ajouterAsync(i, j);
        }
        
        public double puissance(double a, double b) {
            return base.Channel.puissance(a, b);
        }
        
        public System.Threading.Tasks.Task<double> puissanceAsync(double a, double b) {
            return base.Channel.puissanceAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoResponse ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap.GetToto(ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequest request) {
            return base.Channel.GetToto(request);
        }
        
        public ConsumerService.fr.afcepf.ai102.service.dotnet.Toto GetToto() {
            ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequest inValue = new ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequest();
            inValue.Body = new ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequestBody();
            ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoResponse retVal = ((ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap)(this)).GetToto(inValue);
            return retVal.Body.GetTotoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoResponse> ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap.GetTotoAsync(ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequest request) {
            return base.Channel.GetTotoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoResponse> GetTotoAsync() {
            ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequest inValue = new ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequest();
            inValue.Body = new ConsumerService.fr.afcepf.ai102.service.dotnet.GetTotoRequestBody();
            return ((ConsumerService.fr.afcepf.ai102.service.dotnet.PremierServiceDotNetSoap)(this)).GetTotoAsync(inValue);
        }
    }
}
