
package fr.afcepf.ai102.service.dotnet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PremierServiceDotNetSoap", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PremierServiceDotNetSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://dotnet.service.ai102.afcepf.fr/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/", className = "fr.afcepf.ai102.service.dotnet.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/", className = "fr.afcepf.ai102.service.dotnet.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param i
     * @param j
     * @return
     *     returns int
     */
    @WebMethod(action = "http://dotnet.service.ai102.afcepf.fr/ajouter")
    @WebResult(name = "ajouterResult", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/")
    @RequestWrapper(localName = "ajouter", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/", className = "fr.afcepf.ai102.service.dotnet.Ajouter")
    @ResponseWrapper(localName = "ajouterResponse", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/", className = "fr.afcepf.ai102.service.dotnet.AjouterResponse")
    public int ajouter(
        @WebParam(name = "i", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/")
        int i,
        @WebParam(name = "j", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/")
        int j);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns double
     */
    @WebMethod(action = "http://dotnet.service.ai102.afcepf.fr/puissance")
    @WebResult(name = "puissanceResult", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/")
    @RequestWrapper(localName = "puissance", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/", className = "fr.afcepf.ai102.service.dotnet.Puissance")
    @ResponseWrapper(localName = "puissanceResponse", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/", className = "fr.afcepf.ai102.service.dotnet.PuissanceResponse")
    public double puissance(
        @WebParam(name = "a", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/")
        double a,
        @WebParam(name = "b", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/")
        double b);

    /**
     * 
     * @return
     *     returns fr.afcepf.ai102.service.dotnet.Toto
     */
    @WebMethod(operationName = "GetToto", action = "http://dotnet.service.ai102.afcepf.fr/GetToto")
    @WebResult(name = "GetTotoResult", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/")
    @RequestWrapper(localName = "GetToto", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/", className = "fr.afcepf.ai102.service.dotnet.GetToto")
    @ResponseWrapper(localName = "GetTotoResponse", targetNamespace = "http://dotnet.service.ai102.afcepf.fr/", className = "fr.afcepf.ai102.service.dotnet.GetTotoResponse")
    public Toto getToto();

}
