
package fr.afcepf.ai102.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculSWService", targetNamespace = "http://impl.service.ai102.afcepf.fr", wsdlLocation = "http://localhost:8080/PremierService_AXIS/services/CalculSW?wsdl")
public class CalculSWService
    extends Service
{

    private final static URL CALCULSWSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULSWSERVICE_EXCEPTION;
    private final static QName CALCULSWSERVICE_QNAME = new QName("http://impl.service.ai102.afcepf.fr", "CalculSWService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PremierService_AXIS/services/CalculSW?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULSWSERVICE_WSDL_LOCATION = url;
        CALCULSWSERVICE_EXCEPTION = e;
    }

    public CalculSWService() {
        super(__getWsdlLocation(), CALCULSWSERVICE_QNAME);
    }

    public CalculSWService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULSWSERVICE_QNAME, features);
    }

    public CalculSWService(URL wsdlLocation) {
        super(wsdlLocation, CALCULSWSERVICE_QNAME);
    }

    public CalculSWService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULSWSERVICE_QNAME, features);
    }

    public CalculSWService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculSWService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculSW
     */
    @WebEndpoint(name = "CalculSW")
    public CalculSW getCalculSW() {
        return super.getPort(new QName("http://impl.service.ai102.afcepf.fr", "CalculSW"), CalculSW.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculSW
     */
    @WebEndpoint(name = "CalculSW")
    public CalculSW getCalculSW(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.ai102.afcepf.fr", "CalculSW"), CalculSW.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULSWSERVICE_EXCEPTION!= null) {
            throw CALCULSWSERVICE_EXCEPTION;
        }
        return CALCULSWSERVICE_WSDL_LOCATION;
    }

}
