
package fr.afcepf.ai102.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculSW", targetNamespace = "http://impl.service.ai102.afcepf.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculSW {


    /**
     * 
     * @param paramI
     * @param paramJ
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://impl.service.ai102.afcepf.fr")
    @RequestWrapper(localName = "add", targetNamespace = "http://impl.service.ai102.afcepf.fr", className = "fr.afcepf.ai102.service.impl.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://impl.service.ai102.afcepf.fr", className = "fr.afcepf.ai102.service.impl.AddResponse")
    public int add(
        @WebParam(name = "paramI", targetNamespace = "http://impl.service.ai102.afcepf.fr")
        int paramI,
        @WebParam(name = "paramJ", targetNamespace = "http://impl.service.ai102.afcepf.fr")
        int paramJ);

    /**
     * 
     * @param paramA
     * @param paramB
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "powReturn", targetNamespace = "http://impl.service.ai102.afcepf.fr")
    @RequestWrapper(localName = "pow", targetNamespace = "http://impl.service.ai102.afcepf.fr", className = "fr.afcepf.ai102.service.impl.Pow")
    @ResponseWrapper(localName = "powResponse", targetNamespace = "http://impl.service.ai102.afcepf.fr", className = "fr.afcepf.ai102.service.impl.PowResponse")
    public double pow(
        @WebParam(name = "paramA", targetNamespace = "http://impl.service.ai102.afcepf.fr")
        double paramA,
        @WebParam(name = "paramB", targetNamespace = "http://impl.service.ai102.afcepf.fr")
        double paramB);

}
